[dev]
command = "npm run dev"
framework = "astro"

[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions/"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/sitemap-index.xml"
to = "/sitemap-index.xml"
status = 200

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
